Vagrant.configure(2) do |config|

  config.vm.define "jenkins2" do |jenkins2|
    jenkins2.vm.box = "centos/7"
    jenkins2.vm.hostname = "jenkins2"
    jenkins2.vm.network "forwarded_port", guest: 8080, host: 8888
    jenkins2.vm.network "private_network", ip: "10.0.15.24"
    jenkins2.vm.disk :disk, name: "storage", size: "20GB"
  end

  config.vm.provider "virtualbox" do |v|
    v.name = "jenkins2"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    yum install -y git vim lsof net-tools 
    yum install -y yum-utils
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    systemctl start docker
    systemctl enable docker
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    docker run -d --name jenkins -p 8080:8080 -p 50000:50000 -d -v jenkins:/var/jenkins_home jenkins/jenkins:lts
  SHELL

end
